apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    app: notebook-controller
    app.kubernetes.io/component: notebook-controller
    app.kubernetes.io/instance: notebook-controller-v0.7.0
    app.kubernetes.io/managed-by: kfctl
    app.kubernetes.io/name: notebook-controller
    app.kubernetes.io/part-of: kubeflow
    app.kubernetes.io/version: v0.7.0
    kustomize.component: notebook-controller
  name: notebooks.kubeflow.org
spec:
  group: kubeflow.org
  names:
    kind: Notebook
    plural: notebooks
    singular: notebook
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            template:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "make" to regenerate code after modifying this file'
              properties:
                spec:
                  type: object
              type: object
          type: object
        status:
          properties:
            conditions:
              description: Conditions is an array of current conditions
              items:
                properties:
                  type:
                    description: Type of the confition/
                    type: string
                required:
                - type
                type: object
              type: array
          required:
          - conditions
          type: object
  versions:
  - name: v1alpha1
    served: true
    storage: false
  - name: v1beta1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: notebook-controller
    app.kubernetes.io/component: notebook-controller
    app.kubernetes.io/instance: notebook-controller-v0.7.0
    app.kubernetes.io/managed-by: kfctl
    app.kubernetes.io/name: notebook-controller
    app.kubernetes.io/part-of: kubeflow
    app.kubernetes.io/version: v0.7.0
    kustomize.component: notebook-controller
  name: notebook-controller-service-account
  namespace: kubeflow
---
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      rbac.authorization.kubeflow.org/aggregate-to-kubeflow-notebooks-admin: "true"
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: notebook-controller
    app.kubernetes.io/component: notebook-controller
    app.kubernetes.io/instance: notebook-controller-v0.7.0
    app.kubernetes.io/managed-by: kfctl
    app.kubernetes.io/name: notebook-controller
    app.kubernetes.io/part-of: kubeflow
    app.kubernetes.io/version: v0.7.0
    kustomize.component: notebook-controller
    rbac.authorization.kubeflow.org/aggregate-to-kubeflow-admin: "true"
  name: notebook-controller-kubeflow-notebooks-admin
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: notebook-controller
    app.kubernetes.io/component: notebook-controller
    app.kubernetes.io/instance: notebook-controller-v0.7.0
    app.kubernetes.io/managed-by: kfctl
    app.kubernetes.io/name: notebook-controller
    app.kubernetes.io/part-of: kubeflow
    app.kubernetes.io/version: v0.7.0
    kustomize.component: notebook-controller
    rbac.authorization.kubeflow.org/aggregate-to-kubeflow-edit: "true"
    rbac.authorization.kubeflow.org/aggregate-to-kubeflow-notebooks-admin: "true"
  name: notebook-controller-kubeflow-notebooks-edit
rules:
- apiGroups:
  - kubeflow.org
  resources:
  - notebooks
  - notebooks/status
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - deletecollection
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: notebook-controller
    app.kubernetes.io/component: notebook-controller
    app.kubernetes.io/instance: notebook-controller-v0.7.0
    app.kubernetes.io/managed-by: kfctl
    app.kubernetes.io/name: notebook-controller
    app.kubernetes.io/part-of: kubeflow
    app.kubernetes.io/version: v0.7.0
    kustomize.component: notebook-controller
    rbac.authorization.kubeflow.org/aggregate-to-kubeflow-view: "true"
  name: notebook-controller-kubeflow-notebooks-view
rules:
- apiGroups:
  - kubeflow.org
  resources:
  - notebooks
  - notebooks/status
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: notebook-controller
    app.kubernetes.io/component: notebook-controller
    app.kubernetes.io/instance: notebook-controller-v0.7.0
    app.kubernetes.io/managed-by: kfctl
    app.kubernetes.io/name: notebook-controller
    app.kubernetes.io/part-of: kubeflow
    app.kubernetes.io/version: v0.7.0
    kustomize.component: notebook-controller
  name: notebook-controller-role
rules:
- apiGroups:
  - apps
  resources:
  - statefulsets
  - deployments
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - '*'
- apiGroups:
  - kubeflow.org
  resources:
  - notebooks
  - notebooks/status
  verbs:
  - '*'
- apiGroups:
  - networking.istio.io
  resources:
  - virtualservices
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: notebook-controller
    app.kubernetes.io/component: notebook-controller
    app.kubernetes.io/instance: notebook-controller-v0.7.0
    app.kubernetes.io/managed-by: kfctl
    app.kubernetes.io/name: notebook-controller
    app.kubernetes.io/part-of: kubeflow
    app.kubernetes.io/version: v0.7.0
    kustomize.component: notebook-controller
  name: notebook-controller-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: notebook-controller-role
subjects:
- kind: ServiceAccount
  name: notebook-controller-service-account
  namespace: kubeflow
---
apiVersion: v1
data:
  ISTIO_GATEWAY: kubeflow/kubeflow-gateway
  POD_LABELS: gcp-cred-secret=user-gcp-sa,gcp-cred-secret-filename=user-gcp-sa.json
  USE_ISTIO: "true"
kind: ConfigMap
metadata:
  annotations: {}
  labels:
    app: notebook-controller
    app.kubernetes.io/component: notebook-controller
    app.kubernetes.io/instance: notebook-controller-v0.7.0
    app.kubernetes.io/managed-by: kfctl
    app.kubernetes.io/name: notebook-controller
    app.kubernetes.io/part-of: kubeflow
    app.kubernetes.io/version: v0.7.0
    kustomize.component: notebook-controller
  name: notebook-controller-parameters
  namespace: kubeflow
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: notebook-controller
    app.kubernetes.io/component: notebook-controller
    app.kubernetes.io/instance: notebook-controller-v0.7.0
    app.kubernetes.io/managed-by: kfctl
    app.kubernetes.io/name: notebook-controller
    app.kubernetes.io/part-of: kubeflow
    app.kubernetes.io/version: v0.7.0
    kustomize.component: notebook-controller
  name: notebook-controller-service
  namespace: kubeflow
spec:
  ports:
  - port: 443
  selector:
    app: notebook-controller
    app.kubernetes.io/component: notebook-controller
    app.kubernetes.io/instance: notebook-controller-v0.7.0
    app.kubernetes.io/managed-by: kfctl
    app.kubernetes.io/name: notebook-controller
    app.kubernetes.io/part-of: kubeflow
    app.kubernetes.io/version: v0.7.0
    kustomize.component: notebook-controller
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: notebook-controller
    app.kubernetes.io/component: notebook-controller
    app.kubernetes.io/instance: notebook-controller-v0.7.0
    app.kubernetes.io/managed-by: kfctl
    app.kubernetes.io/name: notebook-controller
    app.kubernetes.io/part-of: kubeflow
    app.kubernetes.io/version: v0.7.0
    kustomize.component: notebook-controller
  name: notebook-controller-deployment
  namespace: kubeflow
spec:
  selector:
    matchLabels:
      app: notebook-controller
      app.kubernetes.io/component: notebook-controller
      app.kubernetes.io/instance: notebook-controller-v0.7.0
      app.kubernetes.io/managed-by: kfctl
      app.kubernetes.io/name: notebook-controller
      app.kubernetes.io/part-of: kubeflow
      app.kubernetes.io/version: v0.7.0
      kustomize.component: notebook-controller
  template:
    metadata:
      labels:
        app: notebook-controller
        app.kubernetes.io/component: notebook-controller
        app.kubernetes.io/instance: notebook-controller-v0.7.0
        app.kubernetes.io/managed-by: kfctl
        app.kubernetes.io/name: notebook-controller
        app.kubernetes.io/part-of: kubeflow
        app.kubernetes.io/version: v0.7.0
        kustomize.component: notebook-controller
    spec:
      containers:
      - command:
        - /manager
        env:
        - name: USE_ISTIO
          value: "true"
        - name: ISTIO_GATEWAY
          value: kubeflow/kubeflow-gateway
        - name: POD_LABELS
          value: gcp-cred-secret=user-gcp-sa,gcp-cred-secret-filename=user-gcp-sa.json
        image: gcr.io/kubeflow-images-public/notebook-controller@sha256:6490f737000bd1d2520ac4b8cbde2b09749cdb291b1967ddda95d05131db49db
        imagePullPolicy: Always
        name: manager
      serviceAccountName: notebook-controller-service-account
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  labels:
    app.kubernetes.io/component: notebook-controller
    app.kubernetes.io/instance: notebook-controller-v0.7.0
    app.kubernetes.io/managed-by: kfctl
    app.kubernetes.io/name: notebook-controller
    app.kubernetes.io/part-of: kubeflow
    app.kubernetes.io/version: v0.7.0
  name: notebook-controller
  namespace: kubeflow
spec:
  addOwnerRef: true
  componentKinds:
  - group: core
    kind: Service
  - group: apps
    kind: Deployment
  - group: core
    kind: ServiceAccount
  descriptor:
    description: Notebooks controller allows users to create a custom resource \"Notebook\"
      (jupyter notebook).
    keywords:
    - jupyter
    - notebook
    - notebook-controller
    - jupyterhub
    links:
    - description: About
      url: https://github.com/kubeflow/kubeflow/tree/master/components/notebook-controller
    maintainers:
    - email: lunkai@google.com
      name: Lun-kai Hsu
    owners:
    - email: lunkai@gogle.com
      name: Lun-kai Hsu
    type: notebook-controller
    version: v1beta1
  selector:
    matchLabels:
      app.kubernetes.io/component: notebook-controller
      app.kubernetes.io/instance: notebook-controller-v0.7.0
      app.kubernetes.io/managed-by: kfctl
      app.kubernetes.io/name: notebook-controller
      app.kubernetes.io/part-of: kubeflow
      app.kubernetes.io/version: v0.7.0
